import { useState } from "react";
import type { Route } from "./+types/psle-math-number-patterns";
import { ArrowLeft, Brain, CheckCircle, Eye, EyeOff } from "lucide-react";
import { Link } from "react-router";

export function meta({ }: Route.MetaArgs) {
  return [
    { title: "Number Patterns (找规律与数列) - PSLE Math" },
    { name: "description", content: "Master Number Patterns for PSLE Math with detailed explanations and 10 practice questions." },
  ];
}

const explanations = [
  {
    title: "1. Constant Difference (等差数列)",
    desc: "A sequence where the difference between consecutive terms is always the same. To find the Nth term, use the formula: First Term + (N - 1) × Difference.",
    example: "Sequence: 5, 8, 11, 14, ... (Difference is +3). The 10th term = 5 + (10 - 1) × 3 = 5 + 27 = 32."
  },
  {
    title: "2. Square Numbers (平方数)",
    desc: "Numbers generated by multiplying a number by itself: 1×1, 2×2, 3×3. Often represented as squares made of dots.",
    example: "Sequence: 1, 4, 9, 16, 25, ... The Nth term is N × N."
  },
  {
    title: "3. Triangular Numbers (三角形数)",
    desc: "Numbers that can form an equilateral triangle of dots. The sequence is formed by adding 2, then 3, then 4, etc.",
    example: "Sequence: 1, 3, 6, 10, 15, ... The formula for the Nth term is (N × (N + 1)) / 2."
  },
  {
    title: "4. Repeating Patterns (循环规律)",
    desc: "Patterns that repeat a set of items endlessly. To find a term far ahead, divide the position by the length of the repeating block and look at the remainder.",
    example: "Pattern: A, B, C, A, B, C, A... What is the 14th letter? The block 'A, B, C' has length 3. 14 ÷ 3 = 4 remainder 2. The 2nd item in the block is B."
  }
];

const questions = [
  {
    id: 1,
    type: "Constant Difference",
    question: "Find the 50th term in the sequence: 4, 9, 14, 19, 24, ...",
    solution: "The difference between terms is +5.\nFormula: First term + (N - 1) × Difference\n50th term = 4 + (50 - 1) × 5 = 4 + 49 × 5 = 4 + 245 = 249."
  },
  {
    id: 2,
    type: "Matchsticks Pattern",
    question: "Figure 1 is made of 4 matchsticks forming a square. Figure 2 is made of 7 matchsticks forming a row of 2 squares. Figure 3 is made of 10 matchsticks forming 3 squares. How many matchsticks are needed for Figure 20?",
    solution: "The sequence is 4, 7, 10, ... (Starts at 4, adds 3 each time).\n20th term = 4 + (20 - 1) × 3 = 4 + 19 × 3 = 4 + 57 = 61 matchsticks."
  },
  {
    id: 3,
    type: "Square Numbers",
    question: "Find the 15th term of the sequence: 1, 4, 9, 16, 25, ...",
    solution: "These are square numbers (N × N).\nFor the 15th term, the value is 15 × 15 = 225."
  },
  {
    id: 4,
    type: "Repeating Pattern",
    question: "A string of beads follows the color pattern: Red, Blue, Green, Yellow, Red, Blue, Green, Yellow... What color is the 103rd bead?",
    solution: "The pattern repeats every 4 beads (Red, Blue, Green, Yellow).\n103 ÷ 4 = 25 remainder 3.\nThe remainder is 3, so we look at the 3rd bead in the pattern, which is Green."
  },
  {
    id: 5,
    type: "Triangular Numbers",
    question: "A caterer is stacking oranges in a triangular pyramid shape. The top layer has 1 orange, the 2nd layer has 3 oranges, the 3rd layer has 6 oranges, and the 4th layer has 10 oranges. How many oranges are in the 8th layer?",
    solution: "The sequence is 1, 3, 6, 10, ... (Adding +2, +3, +4...)\n5th layer: 10 + 5 = 15\n6th layer: 15 + 6 = 21\n7th layer: 21 + 7 = 28\n8th layer: 28 + 8 = 36 oranges."
  },
  {
    id: 6,
    type: "Fibonacci Sequence",
    question: "Look at the sequence: 1, 1, 2, 3, 5, 8, 13... What is the sum of the 9th and 10th terms?",
    solution: "Each term is the sum of the two previous terms.\n8th term = 5 + 8 = 13\n9th term = 8 + 13 = 21\n10th term = 13 + 21 = 34\nSum = 21 + 34 = 55."
  },
  {
    id: 7,
    type: "Decreasing Pattern",
    question: "Find the missing term in the sequence: 100, 93, 86, 79, __, 65, 58.",
    solution: "The difference between each term is -7.\n79 - 7 = 72.\nThe missing term is 72."
  },
  {
    id: 8,
    type: "Fraction Pattern",
    question: "Consider the sequence: 1/2, 2/3, 3/4, 4/5, ... What is the 99th term?",
    solution: "The numerator is the same as the position number N. The denominator is N + 1.\nFor the 99th term, the numerator is 99 and the denominator is 99 + 1 = 100.\nThe fraction is 99/100."
  },
  {
    id: 9,
    type: "Two Alternating Sequences",
    question: "Find the 10th term in the sequence: 2, 10, 4, 9, 6, 8, 8, 7, ...",
    solution: "The sequence alternates between two patterns:\nOdd positions (1st, 3rd, 5th...): 2, 4, 6, 8, 10 (Adding 2)\nEven positions (2nd, 4th, 6th...): 10, 9, 8, 7, 6 (Subtracting 1)\nThe 10th term is the 5th number of the Even positions pattern, which is 6."
  },
  {
    id: 10,
    type: "Complex Formula",
    question: "A sequence of numbers is formed by multiplying the position number by 3 and then subtracting 1. (Formula: 3N - 1). What is the sum of the 10th term and 20th term?",
    solution: "10th term = (3 × 10) - 1 = 29\n20th term = (3 × 20) - 1 = 59\nSum = 29 + 59 = 88."
  }
];

export default function NumberPatterns() {
  const [showAnswers, setShowAnswers] = useState<{ [key: number]: boolean }>({});

  const toggleAnswer = (id: number) => {
    setShowAnswers(prev => ({
      ...prev,
      [id]: !prev[id]
    }));
  };

  return (
    <div className="min-h-screen bg-[#f6f6f3] p-6 font-sans pb-24">
      <div className="max-w-4xl mx-auto">
        <header className="flex flex-col md:flex-row md:items-center gap-4 py-8 mb-4">
          <Link to="/math-syllabus" className="w-10 h-10 bg-white rounded-full flex items-center justify-center shadow-sm hover:bg-gray-50 transition-colors text-gray-700 flex-shrink-0">
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <div>
            <h1 className="text-4xl font-extrabold text-[#211922] tracking-tight">找规律与数列 (Number Patterns)</h1>
            <p className="text-[#62625b] mt-2 text-lg">Master sequences, visual patterns, and Nth term formulas for PSLE Math.</p>
          </div>
        </header>

        {/* Detailed Explanation Section */}
        <section className="mb-12 animate-in fade-in slide-in-from-bottom-4 duration-500">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 bg-[#435ee5] rounded-xl flex items-center justify-center text-white shadow-md">
              <Brain className="w-5 h-5" />
            </div>
            <h2 className="text-2xl font-bold text-[#211922]">核心知识点解析 (Key Concepts)</h2>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {explanations.map((exp, idx) => (
              <div key={idx} className="bg-white p-6 rounded-3xl shadow-sm border border-gray-100">
                <h3 className="text-xl font-bold text-[#435ee5] mb-3">{exp.title}</h3>
                <p className="text-gray-700 text-sm leading-relaxed mb-4">{exp.desc}</p>
                <div className="bg-blue-50 p-4 rounded-2xl border border-blue-100">
                  <p className="text-blue-900 text-sm font-medium">💡 例题: {exp.example}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Practice Questions Section */}
        <section className="animate-in fade-in slide-in-from-bottom-6 duration-700">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 bg-[#e60023] rounded-xl flex items-center justify-center text-white shadow-md">
              <CheckCircle className="w-5 h-5" />
            </div>
            <h2 className="text-2xl font-bold text-[#211922]">实战练习 (Practice Questions)</h2>
          </div>
          <p className="text-gray-600 mb-6">Try to solve these 10 questions before checking the answers!</p>

          <div className="space-y-6">
            {questions.map((q, idx) => (
              <div key={idx} className="bg-white p-6 md:p-8 rounded-3xl shadow-sm border border-gray-100 transition-all">
                <div className="flex items-center justify-between mb-4 border-b border-gray-100 pb-4">
                  <span className="font-bold text-gray-900 text-lg">Question {q.id}</span>
                  <span className="text-xs font-bold bg-gray-100 text-gray-600 px-3 py-1 rounded-full uppercase tracking-wide">
                    {q.type}
                  </span>
                </div>
                
                <p className="text-gray-800 text-lg leading-relaxed mb-6 font-medium">
                  {q.question}
                </p>

                <button 
                  onClick={() => toggleAnswer(q.id)}
                  className={`flex items-center gap-2 px-5 py-2.5 rounded-full font-bold text-sm transition-all ${showAnswers[q.id] ? 'bg-gray-100 text-gray-700' : 'bg-[#e60023] text-white hover:bg-red-700'}`}
                >
                  {showAnswers[q.id] ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                  {showAnswers[q.id] ? "Hide Answer" : "Show Answer & Working"}
                </button>

                {showAnswers[q.id] && (
                  <div className="mt-6 bg-green-50 p-6 rounded-2xl border border-green-200 animate-in fade-in duration-300">
                    <h4 className="font-bold text-green-900 mb-2">Solution:</h4>
                    <p className="text-green-800 whitespace-pre-line leading-relaxed">
                      {q.solution}
                    </p>
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>

      </div>
    </div>
  );
}
